[package]
name = "rawio-core"
description = "Raw offset read/write over removable block devices"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys.workspace = true

[lints]
workspace = true
